### ISSUE TITLE
date_repeat Module Status

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/date_repeat#11]
Hi Graham, is it too early for user testing on this module?  I installed it to test it, but could not get very far.

**Comment by Graham-72** [comment]
@Dinornis I started this port when I was interested in getting Calendar ported to Backdrop but I have abandoned both projects.

**Comment by Dinornis** [comment]
Thanks, it may be a good to add that information to the Status section of the Readme.md file for both contributions.

**Comment by herbdool** [comment]
@Graham-72 can you also update the Readme or description that you're seeking someone to take this over?

**Comment by laryn** [comment]
@Graham-72 I think I'll need this soon and may try to get it up and running. Are you willing to make me the maintainer? PR: https://github.com/backdrop-contrib/date_repeat/pull/12

**Comment by laryn** [comment]
I'm working on this module so will close this issue for now.
