### ISSUE TITLE
Notice: Undefined index: #title in _date_popup_process_date_part

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/date_repeat#13]
Seeing this when trying to add content that includes a date field (on a Drupal 7 upgrade in process):

> Notice: Undefined index: #title in _date_popup_process_date_part() (line 1073 of /app/core/modules/date/date.elements.inc).

> Notice: Undefined index: #title in date_popup_element_process() (line 986 of /app/core/modules/date/date.elements.inc).

**Comment by herbdool** [comment]
I think I fixed this as part of other fixes.
