### ISSUE TITLE
When editing repeating dates they don't show in the correct format

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/date_repeat#16]
Adding a repeating date seems to mostly work as expected (with a lot of https://github.com/backdrop-contrib/date_repeat/issues/13) but when editing the content again, the date is displayed in more of a standard multi-value display rather than the repeating date format:

# Adding a date

![Screen Shot 2020-12-09 at 11 58 27 AM](https://user-images.githubusercontent.com/871421/101668386-19b64800-3a16-11eb-9241-69543dca35c5.jpg)

 - I don't think it should have the handlebar or the "Add another item" button

# Viewing a date

![Screen Shot 2020-12-09 at 11 59 06 AM](https://user-images.githubusercontent.com/871421/101668447-2cc91800-3a16-11eb-9cdc-0f22490ea8f4.jpg)

# Editing a date

![Screen Shot 2020-12-09 at 11 59 46 AM](https://user-images.githubusercontent.com/871421/101668468-3488bc80-3a16-11eb-8c42-3ef8fc65988d.jpg)

 - Should display more like the first screenshot with the repeating date form rather than the standard multi-value form

**Comment by indigoxela** [comment]
Yes, see issue #18 for the reason. The field values get saved properly, but the repeat rule is lost.

**Comment by laryn** [comment]
Closing this issue since it's basically describing the same issue as #18
