### ISSUE TITLE
Is there a plan to complete the port?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/date_repeat#17]
This is a very nice module and I would need it in three migration projects (D7 sites to Backdrop). It would be very helpful to have this working :-)

**Comment by laryn** [comment]
Hi @djzwerg -- yes, I plan to complete the port but I am working it into projects as I can. I don't have any dedicated funding for this and am doing it as I can at the moment.

I also accept PRs and any other types of helpful input. 😉

**Comment by djzwerg** [comment]
Hi @laryn. I'm sorry but I can't help with a PR or so. I don't have enough coding skills :-(

**Comment by laryn** [comment]
No worries @djzwerg!

**Comment by djzwerg** [comment]
@laryn I know you have lots of projects to contribute. Well I asked about funding but it isn't as easy as I thought because the websites I'm going to migrate are provided by non-profit organizations (e. g. museum, hobby pages, free WLAN projects).

**Comment by laryn** [comment]
@djzwerg I understand. Those sites seems like great fits for Backdrop!

I do plan to get to this eventually. I did a little scanning today to take stock and may have identified another issue that could be the key. I'll file that issue.

**Comment by djzwerg** [comment]
Hi @laryn I saw this release today: https://github.com/backdrop-contrib/repeating_dates. Maybe it would help to fix the issues?

**Comment by indigoxela** [comment]
> Maybe it would help to fix the issues?

@djzwerg I'm afraid I have to disappoint you. The other module (repeating_dates) has been created from scratch, because we didn't find a way to complete the port of date_repeat. These modules are completely different.

**Comment by laryn** [comment]
@djzwerg I recommend moving to https://github.com/backdrop-contrib/repeating_dates from @indigoxela because we've discovered this module is not able to be ported within the existing the framework. (Backdrop's approach has made the hacky way this module modified the database schema in Drupal 7 not a viable option here). I'm updating the README with this information.
