### ISSUE TITLE
Need to replace a date_api function.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/date_repeat#2]
There are several lines
`
module_load_include('inc', 'date_api', 'date_api_ical');
`
but no longer a file date_api_ical.inc ?

**Comment by Graham-72** [comment]
Also restructured to add an includes directory with commit 6527b5a4936c735a3a7c6dc333029212109066ec

**Comment by laryn** [comment]
Closing -- reopen or make a new issue if needed.
