### ISSUE TITLE
Missing functions from date_api()

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/date_repeat#3]
date_repeat.inc requires function date_order_translated() from Drupal's date_api.module.

**Comment by laryn** [comment]
It's conceivable (if not likely) that this could eventually get into core with the same function name, perhaps better to rename the function/calls from `date_order_translated()` to `date_order_translated()` to prevent hypothetical future clashes.

**Comment by laryn** [comment]
Broadened this a bit and tried to rearrange so they are all collected in one place rather than scattered throughout...
