### ISSUE TITLE
Missing function date_get_entity_bundle

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/date_repeat#4]
function date_get_entity_bundle used to be in date.module. I am now getting

Fatal error: Call to undefined function date_get_entity_bundle() in /var/www/vhosts/oliverweb.net/httpdocs/backdrop200/modules/date_repeat/date_repeat_field/date_repeat_field.module on line 136

when I try to view any page containing a date field.

**Comment by Graham-72** [comment]
This is happening in function date_repeat_field_show, the purpose of which is to
"See if the user can access repeat date info for this entity."

**Comment by laryn** [comment]
It's conceivable (if not likely) that this could eventually get into core with the same function name, perhaps better to rename the function/calls from `date_get_entity_bundle()` to `date_repeat_get_entity_bundle()` to prevent hypothetical future clashes.
